name = "CompScienceMeshes"
uuid = "3e66a162-7b8c-5da0-b8f8-124ecd2c3ae1"
version = "0.6.1"

[deps]
ClusterTrees = "5100927d-02aa-593a-b4f9-7235df19f0db"
CollisionDetection = "2b5bf9a6-f3f8-5352-af9c-82bb4af718d8"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
GmshTools = "82e2f556-b1bd-5f1a-9576-f93c0da5f0ee"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
ClusterTrees = "^0.2"
CollisionDetection = "^0.1.5"
Combinatorics = "^0.6, ^0.7, ^1"
Compat = "^1, ^2, ^3, ^4"
DataStructures = "^0.17, ^0.18"
DelimitedFiles = "1"
FastGaussQuadrature = "^0.3, ^0.4, ^0.5, ^1"
GmshTools = "^0.5"
Requires = "^0.5.2, ^1"
StaticArrays = "^0.10, ^0.11, ^0.12, ^1"
julia = "^1.3"

[extras]
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["InteractiveUtils", "LinearAlgebra", "SparseArrays", "Test"]
