name = "CompScienceMeshes"
uuid = "3e66a162-7b8c-5da0-b8f8-124ecd2c3ae1"
version = "0.10.0"

[deps]
ClusterTrees = "5100927d-02aa-593a-b4f9-7235df19f0db"
CollisionDetection = "2b5bf9a6-f3f8-5352-af9c-82bb4af718d8"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
Gmsh = "705231aa-382f-11e9-3f0c-b7cb4346fdeb"
GmshTools = "82e2f556-b1bd-5f1a-9576-f93c0da5f0ee"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Permutations = "2ae35dd2-176d-5d53-8349-f30d82d94d4f"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[compat]
ClusterTrees = "^0.2"
CollisionDetection = "^0.1.5"
Combinatorics = "^0.6, ^0.7, ^1"
Compat = "^1, ^2, ^3, ^4"
DataStructures = "^0.17, ^0.18, 0.19"
DelimitedFiles = "1"
FastGaussQuadrature = "^0.3, ^0.4, ^0.5, ^1"
Gmsh = "0.3"
GmshTools = "^0.5"
Permutations = "0.4.21"
PlotlyBase = "0.8.21"
Requires = "^0.5.2, ^1"
StaticArrays = "^0.10, ^0.11, ^0.12, ^1"
TestItemRunner = "0.2.3"
TestItems = "0.1.1, 1.0"
julia = "^1.10"

[extras]
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PlotlyBase = "a03496cd-edff-5a9b-9e67-9cda94a718b5"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[targets]
test = ["InteractiveUtils", "LinearAlgebra", "PlotlyBase", "SparseArrays", "Test", "TestItems", "TestItemRunner"]
